apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.clusterip.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.deployment.appName }}
  ports:
    - name: {{ .Values.deployment.ports.managment }}
      protocol: TCP
      port: 15672
      targetPort: {{ .Values.deployment.ports.managment }}
    - name: {{ .Values.deployment.ports.message }}
      protocol: TCP
      port: 5672
      targetPort: {{ .Values.deployment.ports.message }}
