apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.mq.clusterIp.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.deployment.appName }}
  ports:
    - name: {{ .Values.deployment.ports.management }}
      protocol: TCP
      port: {{ .Values.global.mq.clusterIp.port }} # external
      targetPort: {{ .Values.deployment.ports.management }} # internal
    - name: {{ .Values.deployment.ports.message }}
      protocol: TCP
      port: 5672 # external
      targetPort: {{ .Values.deployment.ports.message }} # internal
