apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.loadbalancer.name }}
spec:
  selector:
    app: {{ .Values.deployment.appName }}
  type: LoadBalancer
  ports:
    - name: {{ .Values.deployment.ports.managment }}
      protocol: TCP
      port: 15762
      targetPort: {{ .Values.deployment.ports.managment }}
    - name: {{ .Values.deployment.ports.message }}
      protocol: TCP
      port: 5762
      targetPort: {{ .Values.deployment.ports.message }}
