apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: {{ .Values.charts.ingress.hostName }}
      http:
        paths:
          - path: /api/platforms(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.global.platforms.clusterIp.name }}
                port:
                  number: {{ .Values.global.platforms.clusterIp.port }}
          - path: /api/c/platforms
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.global.commands.clusterIp.name }}
                port:
                  number: {{ .Values.global.commands.clusterIp.port }}
    - host: mq.{{ .Values.charts.ingress.hostName }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.global.mq.clusterIp.name }}
                port:
                  number: {{ .Values.global.mq.clusterIp.port }}