apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.platforms.clusterIp.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.deployment.appName }}
  ports:
    - name: {{ .Values.deployment.appName }}
      protocol: TCP
      port: {{ .Values.global.platforms.clusterIp.port }}
      targetPort: 80
    - name: {{ .Values.deployment.ports.grpc.name }}
      protocol: TCP
      port: {{ .Values.deployment.ports.grpc.value }}
      targetPort: {{ .Values.deployment.ports.grpc.value }}
