apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.clusterIp.name }}
spec:
  selector:
    app: {{ .Values.deployment.appName }}
  ports:
    - name: {{ .Values.deployment.appName }}
      protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP