deployment:
  image: mcr.microsoft.com/mssql/server:2017-latest
  name: mssql-depl
  appName: mssql
  volume: mssqldb
  portName: mssql-port
  
pvc:
  name: mssql-pvc
    
nodePort:
  name: mssql-np   

clusterIp:
  name: mssql-clusterip-srv