apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.commands.clusterIp.name }}
spec:
  selector:
    app: {{ .Values.deployment.appName }}
  ports:
    - name: {{ .Values.deployment.appName }}
      protocol: TCP
      port: {{ .Values.global.commands.clusterIp.port }}
      targetPort: 80
  type: ClusterIP