apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.clusterIp.name }}
spec:
  selector:
    app: {{ .Values.deployment.appName }}
  ports:
    - name: {{ .Values.deployment.portName }}
      protocol: TCP
      port: 1433
      targetPort: {{ .Values.deployment.portName }}
  type: ClusterIP