apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.loadbalancer.name }}
spec:
  selector:
    app: {{ .Values.deployment.appName }}
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: LoadBalancer